### ISSUE TITLE
乙级1009部分代码不理解

### ISSUE THREAD

**Issue by Larry2019** [SuYindu/PAT#1]
`#include <stdio.h>

int main() {
    int count = 0;
    char words[85][85];
    while ((scanf("%s", words[count])) != EOF)/*为什么这里不可以把count++去掉直接写成word[count++]，试了编译无法通过，不明白这块的原理*/
        count++;
    for (int i = count - 1; i >= 0; i--)
        printf("%s%c", words[i], i > 0 ? ' ' : '\n');
    return 0;
}`

**Comment by SuYindu** [comment]
Hi, Larry. Thank you for your star!
关于去掉  count++ 后不能通过编译的问题，八成是你把分号一并给删了，注意循环体不能为空。
另外，将count++替换成 word[count++] 的话会导致循环退出的时候 count 多增加一次，即比实际读入的单词数多一。

**Comment by SuYindu** [comment]
> `#include <stdio.h>
> 
> int main() {
> int count = 0;
> char words[85][85];
> while ((scanf("%s", words[count])) != EOF)/_为什么这里不可以把count++去掉直接写成word[count++]，试了编译无法通过，不明白这块的原理_/
> count++;
> for (int i = count - 1; i >= 0; i--)
> printf("%s%c", words[i], i > 0 ? ' ' : '\n');
> return 0;
> }`

Hi, Larry. Thank you for your star!
关于去掉 count++ 后不能通过编译的问题，八成是你把分号一并给删了，注意循环体不能为空。
另外，将 count++ 替换成 word[count++] 的话会导致循环退出的时候 count 多增加一次，即比实际读入的单词数多一。

**Comment by Larry2019** [comment]
Your repository is truly awesome.Thank you for your answer!
