### ISSUE TITLE
1042.cpp compile error

### ISSUE THREAD

**Issue by Larry2019** [SuYindu/PAT#2]
error: 'to_string' was not declared in this scope|

**Comment by SuYindu** [comment]
我的电脑和 PAT 服务器上的编译环境都是能成功编译的。
建议加上 string 头文件试试，应该就能通过了。

**Comment by SuYindu** [comment]
> error: 'to_string' was not declared in this scope|

我的电脑和 PAT 服务器上的编译环境都是能成功编译的。
建议加上 string 头文件试试，应该就能通过了。
